import express from 'express';
import dotenv from 'dotenv';
import morgan from 'morgan';
dotenv.config();
const app = express();
app.use(morgan('dev'));
app.use(express.static('public'));
app.get('/health',(req,res)=>res.json({ok:true}));
const port = process.env.PORT || 10000;
app.listen(port, ()=> console.log('Listening on :' + port));
